### ISSUE TITLE
No Data

### ISSUE THREAD

**Issue by nikit-nl** [mrvanes/MMM-PVoutput#1]
I know its been 4 years for the last update and I dont know if this is working but tried to integrate this in my Magic Mirror setup but i am getting No Data error when the mirror is loading

I made a read only Api in PVoutput 
Config

{
			module: "MMM-PVoutput",
			position: "lower_third",
			config: {
				sid: "62451",
				apiKey: "abcdefgh1234567",
				width: 500,
				height: 300,
				lineWidth: 2,
				showConsumption: true,
				genLineColor: "#e0ffe0",
				genFillColor: "rgba(100, 200, 100, 0.2)",
				consLineColor: "#ffe0e0",
				consFillColor: "rgba(200, 100, 100, 0.2)",
				maxPower: 2500,
				updateInterval: 300000,
				}
		},

**Comment by mrvanes** [comment]
It may have been 4 year, but I'm still actively using the plugin and have no issues?
You can test the actual API call with this curl command:
```
curl -v -H 'X-Pvoutput-Apikey: <api key>' -H 'X-Pvoutput-SystemId: <system id>'http://pvoutput.org/service/r2/getstatus.jsp
```
When I use the above mentioned credentials (please update them asap) I get the following result, which should give a normal graph?
```
...
* Closing connection 0
20200529,12:10,5574,2004,NaN,NaN,0.742,50.8,236.1
```

**Comment by mrvanes** [comment]
I just pulled latest MagicMirror and cloned this repo on my test setup and it still works like a charm?

**Comment by nikit-nl** [comment]
I got the latest version of MagicMirror. installed it today
Tried the Curl command and worked like a charm
* Closing connection 0
20200529,12:45,6774,2100,NaN,NaN,0.778,53.1,235.9

Is there any way I can check why it's not displaying the data?

**Comment by nikit-nl** [comment]
Nevermind, I didn't restart the OS after installing the module.
I thought Ctrl-W was enough to restart the Mirror and Load the module.
Working now!
thanks for the fast reply and the awesome module :D
