### ISSUE TITLE
"No Data" displayed

### ISSUE THREAD

**Issue by martint123** [mrvanes/MMM-PVoutput#2]
MM Newbie warning. 
I have recently started playing with MM and found your pvoutput module.
I have installed it and put in my systemid and api code (tried both main api and public one)
Sadly all that gets displayed is "No Data".

I am running serveronly from a Windows pc that is 24/7.
Any pointers to look for most welcome as I could use a starting point to diagnose.

thanks for your potentially wonderful module
martin

**Comment by martint123** [comment]
My apologies - mysteriously it burst into life after a couple of hours of sitting there.
please ignore

**Comment by mrvanes** [comment]
Good to hear your problem was resolved!
